Made it so that you can change the percentage by 5 percent increments…
nightscout/AndroidAPS pull request #1254
Opened 2022-02-01 00:53 UTC by erobinson

…. the 1 percent changes were too slow for me.

2022-02-01 08:03 UTC, Andries-Smit requested changes
Please review the comments.
After this change is merged, I make sure that the settings is also synced with AAPS watch, 
Similar to #1195

2022-02-08 00:48 UTC, erobinson commented on app/src/main/res/values/strings.xml
> +    <string name="partialboluswizardincrementsize">Change the correction percentage by this much</string>
corrected

2022-02-08 00:48 UTC, erobinson commented on app/src/main/res/values/strings.xml
> +    <string name="key_boluswizard_percentage_increment_size">1</string>
corrected

2022-02-08 00:48 UTC, erobinson commented on app/src/main/res/values/strings.xml
> +    <string name="deliverpartofboluswizardincrementsize"><![CDATA[Each time you click the buttons to change the correction percentage, it will go up or down by this much. So a value of 5 will go 100
corrected

2022-02-08 00:49 UTC, erobinson commented on app/src/main/res/xml/pref_overview.xml
> +                android:key="@string/key_show_profile_button"
It's not, it's something. else I was working on that I accidentally committed.

2022-02-14 08:36 UTC, Andries-Smit commented
@erobinson we could introduce another setting, but do we have to? Should the default for all users be just 5% per click on both the phone and watch app?

2022-02-14 11:05 UTC, erobinson commented
> @erobinson we could introduce another setting, but do we have to? Should the default for all users be just 5% per click on both the phone and watch app?

defaulting to 5% would definitely make it easier. I thought 1% had been done for a reason.

2022-02-18 16:37 UTC, erobinson commented
@Andries-Smit @MilosKozak - I think this should be good to merge now.

2022-02-18 18:47 UTC, Andries-Smit commented
Good to go!

2022-02-24 14:35 UTC, merged