Feature collapsing toolbar to save space
nightscout/AndroidAPS pull request #1632
Opened 2022-04-18 12:13 UTC by osodebailar

As a new feature the Top toolbar can now be scrolled to save space , especially a good thing for smaller displays.
To enable scrolling the <Scroll> Element is replaced by <NestedScrollView> in all fragments. 

Open for discussion or merge if you like

![toolbar_expanded](https://user-images.githubusercontent.com/25795894/163806026-5bde05c2-7fe6-47a8-8a2e-2ea7417934b5.PNG)
![toolbar_scrolled](https://user-images.githubusercontent.com/25795894/163806028-766bd699-7de6-46cf-9d1b-71a409d46406.PNG)

2022-04-18 18:37 UTC, Andries-Smit requested changes
Some minor code formatting requests to change

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/java/info/nightscout/androidaps/MainActivity.kt
> +        //appbar
Please make comment, a single line

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/java/info/nightscout/androidaps/utils/ScrollingOffsetListener.kt
> +        if(firstOffset) {
Please apply code-formatting on the new/changed code (CTRL+ALT+L on Windows or Command+Option+L on Mac.)
If you want to use only a selection, you can use  CTRL+SHIFT+ALT+L on Windows

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/res/layout/activity_logsetting.xml
> +</androidx.core.widget.NestedScrollView>
Please end a file with an empty newline

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/res/layout/activity_main.xml
> +    >
Code formating, will move the > one line up

2022-04-18 18:37 UTC, Andries-Smit commented on automation/src/main/res/layout/automation_dialog_choose_operation.xml
> +</androidx.core.widget.NestedScrollView>
End with empty newline

2022-04-18 18:37 UTC, Andries-Smit commented on automation/src/main/res/layout/automation_dialog_choose_trigger.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on automation/src/main/res/layout/automation_dialog_edit_trigger.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on insight/src/main/res/layout/activity_insight_pairing_information.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on insight/src/main/res/layout/local_insight_fragment.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on rileylink/src/main/res/layout/rileylink_status_general.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
```suggestion
</androidx.constraintlayout.widget.ConstraintLayout>

```

2022-04-18 18:37 UTC, Andries-Smit commented on openhumans/src/main/res/layout/fragment_open_humans_new.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on automation/src/main/res/layout/automation_dialog_event.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on automation/src/main/res/layout/automation_dialog_action.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/res/layout/dialog_wizardinfo.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/res/layout/dialog_treatment.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/res/layout/dialog_tempbasal.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/res/layout/dialog_loop.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/res/layout/dialog_extendedbolus.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/res/layout/dialog_calibration.xml
> +</androidx.core.widget.NestedScrollView>
```suggestion
</androidx.core.widget.NestedScrollView>

```

2022-04-18 18:37 UTC, Andries-Smit commented on app/src/main/res/layout/activity_main.xml
> +</androidx.drawerlayout.widget.DrawerLayout>
```suggestion
</androidx.drawerlayout.widget.DrawerLayout>

```

2022-04-18 18:41 UTC, osodebailar commented
@Andries-Smit how can this happen ?
I replace tags with file Menü : edit->find->replace .

2022-04-18 19:06 UTC, osodebailar commented on app/src/main/java/info/nightscout/androidaps/MainActivity.kt
> +        //appbar
Reformat all files and pushed it

2022-04-18 20:47 UTC, osodebailar commented
Reformat the code and add scrolling flag.
@MilosKozak if you found it useful we can. Merge .

2022-04-19 06:59 UTC, Andries-Smit commented
@osodebailar 
- padding on the bottom seems to be too much
![image](https://user-images.githubusercontent.com/6724749/163943406-a10bd59a-0f01-4a80-9b20-6d43c855531e.png)
- I don't see the `app:layout_scrollFlags="scroll|enterAlways"` behaviour. It always scrolls out and only scrolls in at the top
- Is the scrolling offset listen needed? https://github.com/nightscout/AndroidAPS/pull/1632/files#diff-b72dad13ff175f518b8a844eb878860ba7e4eb41f2a89a7740295c87e07052deR253 I don't see it the samples of https://medium.com/@tonia.tkachuk/appbarlayout-scroll-behavior-with-layout-scrollflags-2eec41b4366b
- What is the correct behaviour when swiping? Should the top bar show when swiping, so the user knows where it goes?

2022-04-19 07:02 UTC, Andries-Smit commented
@osodebailar From a functional perspective. 
Yes, this feature saves space, but is this required? What will be the benefit? And what is the downside? is this only for one screen, or will it affect other screens as well?  Will the navigation toolbar be "missed" at essential times?

2022-04-19 07:06 UTC, osodebailar commented
> @osodebailar
> 
> * padding on the bottom seems to be too much
>   ![image](https://user-images.githubusercontent.com/6724749/163943406-a10bd59a-0f01-4a80-9b20-6d43c855531e.png)
> * I don't see the `app:layout_scrollFlags="scroll|enterAlways"` behaviour. It always scrolls out and only scrolls in at the top
> * Is the scrolling offset listen needed? https://github.com/nightscout/AndroidAPS/pull/1632/files#diff-b72dad13ff175f518b8a844eb878860ba7e4eb41f2a89a7740295c87e07052deR253 I don't see it the samples of https://medium.com/@tonia.tkachuk/appbarlayout-scroll-behavior-with-layout-scrollflags-2eec41b4366b
> * What is the correct behaviour when swiping? Should the top bar show when swiping, so the user knows where it goes?

Yes I also don’t see the behaviour, but it’s not necessary I think. The user knows it after he does it once .
It’s kind of intuitive .

and without the listener the height of the view pager is wrong . In stack overflow i found the solution .

2022-04-19 07:09 UTC, osodebailar commented
> @osodebailar From a functional perspective.
> Yes, this feature saves space, but is this required? What will be the benefit? And what is the downside? is this only for one screen, or will it affect other screens as well? Will the navigation toolbar be "missed" at essential times?

The handling is intuitive and the user will nothing essential missing . 
And required? In my experience , yes .

2022-04-19 20:30 UTC, MilosKozak commented
I don't think this is necessary. I prefer main controls visible all the time

2022-04-19 20:30 UTC, closed without merging