Add friendly relative date display
nightscout/AndroidAPS pull request #243
Opened 2021-01-19 23:03 UTC by jhaydraude

This PR adds a method to DateUtil.java that takes a date and returns a string.

If the date is more than 1 week before or after today, then it returns the original DateUtil.dateString(date)
If the date is today, tomorrow or yesterday then it returns "Today", "Tomorrow" or "Yesterday"
If the date is less than a week out, but not today, tomorrow or yesterday, then it returns "Next <Day Name>" or "Last <Day Name>" 

PR also includes a usage of this method in the Omnipod Overview tab as shown in the screenshot.

Issue: 
https://github.com/MilosKozak/AndroidAPS/issues/3005 

![Screenshot_20210119-173028_AndroidAPS](https://user-images.githubusercontent.com/28458904/105104435-42ebde80-5a80-11eb-966a-1e2aa4330008.png)

2021-01-22 21:25 UTC, AdrianLxM requested changes
Looks like a good addition. I only wonder how well this behaves around midnight?
There are two commented out lines of code. Can they be removed?

2021-01-22 21:25 UTC, AdrianLxM commented on core/src/main/java/info/nightscout/androidaps/utils/DateUtil.java
> +               // friendlyDate = modifier + " " + dayName;
Do you think this commented out lines will be needed in the future?
If not, I'd delete them

2021-01-22 21:25 UTC, AdrianLxM commented on omnipod/src/main/java/info/nightscout/androidaps/plugins/pump/omnipod/ui/OmnipodOverviewFragment.kt
> +    private fun readableZonedTimeRelative(time: DateTime): String {
Not necessarily for this PR, just a remark: There is quite a lot of general format utility functions in a Fragment.
We could move them to DateUtil as well.

2021-09-22 16:13 UTC, MilosKozak commented
@jhaydraude can you finish this PR?

2021-10-04 12:56 UTC, closed without merging