Add search device before Bluetooth connection
nightscout/AndroidAPS pull request #489
Opened 2021-04-22 07:31 UTC by bubbledevteam

Add search device before Bluetooth connection

2021-04-23 22:51 UTC, AdrianLxM requested changes
Thanks for the PR.
I'm not sure if `master` is the correct target or if `dev` would be better.

I do have a few questions I added as inline comments.
Also I wonder if this isn't code duplication with the BLE code in `info.nightscout.androidaps.plugins.pump.common.dialog.RileyLinkBLEConfigActivity` and could be unified?

If it uses scanning all the time - even if not needed - wouldn't the connection then stop as soon as people switch off location on the phone?

2021-04-23 22:51 UTC, AdrianLxM commented on rileylink/src/main/java/info/nightscout/androidaps/plugins/pump/common/hw/rileylink/ble/RileyLinkBLE.java
> +            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
minSDK is 26 -> is there a reason for this distiction?

2021-04-23 22:51 UTC, AdrianLxM commented on rileylink/src/main/java/info/nightscout/androidaps/plugins/pump/common/hw/rileylink/ble/RileyLinkBLE.java
> +    @TargetApi(Build.VERSION_CODES.M)
minSDK is 26. Is this really needed?

2021-04-23 22:51 UTC, AdrianLxM commented on rileylink/src/main/java/info/nightscout/androidaps/plugins/pump/common/hw/rileylink/ble/RileyLinkBLE.java
> +            Platform.get().postDelayedMain(new Runnable() {
Is there a reason to run this on the UI thread?

2021-04-23 22:51 UTC, AdrianLxM commented on rileylink/src/main/java/info/nightscout/androidaps/plugins/pump/common/hw/rileylink/Platform.java
> +    }
This seems to be unused code?

2021-04-23 22:51 UTC, AdrianLxM commented on rileylink/src/main/java/info/nightscout/androidaps/plugins/pump/common/hw/rileylink/Platform.java
> +    }
This seems to be code to detect the platform while we know we are running on Android?

2021-04-23 22:51 UTC, AdrianLxM commented on rileylink/src/main/java/info/nightscout/androidaps/plugins/pump/common/hw/rileylink/ble/RileyLinkBLE.java
> +            e.printStackTrace();
Please use the logger. Especially for such general exceptions.

2021-04-24 11:43 UTC, andyrozman commented
This functionality is totally unnecessary... Once you have RL configured there should be NO MORE search done... We do search in configuration and that is only place this should be done...

2021-04-25 05:40 UTC, bubbledevteam commented
> This functionality is totally unnecessary... Once you have RL configured there should be NO MORE search done... We do search in configuration and that is only place this should be done...

We have tested and found that some Bluetooth devices must be searched before they are connected or they cannot be connected

2021-04-26 03:14 UTC, StephenBrown2 commented
Would this fix the issue where my OrangeLink can't be connected to sometimes if I force close the app or restart my phone?
The only reliable solution I've found in that case is to switch AAPS to Virtual Pump, then open nRF Connect and connect then disconnect from the OrangeLink, then switch AAPS back to Medtronic, and it initializes and connects fine.

2021-04-26 06:17 UTC, bubbledevteam commented
> Would this fix the issue where my OrangeLink can't be connected to sometimes if I force close the app or restart my phone?
> The only reliable solution I've found in that case is to switch AAPS to Virtual Pump, then open nRF Connect and connect then disconnect from the OrangeLink, then switch AAPS back to Medtronic, and it initializes and connects fine.

yes

2021-04-26 08:42 UTC, andyrozman commented
> > This functionality is totally unnecessary... Once you have RL configured there should be NO MORE search done... We do search in configuration and that is only place this should be done...
> 
> We have tested and found that some Bluetooth devices must be searched before they are connected or they cannot be connected

Then please make this optional. So add setting into configuration and users can turn this on or off. Something like "Search for device before connecting" and in description write that some RileyLink replacement require this in brackets OrangeLink. And this should be off by default.

2021-04-26 15:49 UTC, StephenBrown2 commented
Limiting it to "Orange" devices as has been done in [`8a9a5da` (#489)](https://github.com/nightscout/AndroidAPS/pull/489/commits/8a9a5da6f59a52afbffabc50fa64029f16fabc0b) seems like it would be sufficient to me.

2021-04-26 16:48 UTC, andyrozman commented
While this will cover Orange devices, maybe some other users have same problem with EmmaLink or RileyLink, which is why I would like to have this configurable. Using this option might work better on some BT implementations. 

So please make it configurable and then we will need to note this in documentation too, both for MDT and Omnipod.

2021-04-28 03:00 UTC, bubbledevteam commented
> While this will cover Orange devices, maybe some other users have same problem with EmmaLink or RileyLink, which is why I would like to have this configurable. Using this option might work better on some BT implementations.
> 
> So please make it configurable and then we will need to note this in documentation too, both for MDT and Omnipod.

Ok ,I have two designs for the configuration , we can discuss which one is more user friendly.

Design 1: 

![image](https://user-images.githubusercontent.com/53160423/116339929-e2073b80-a810-11eb-9d0e-0010f40c1b15.png)


Design 2:

![image](https://user-images.githubusercontent.com/53160423/116339935-e7648600-a810-11eb-825c-42ad16f1b44a.png)

2021-04-28 05:46 UTC, StephenBrown2 commented
Personally I like the first option.

A note: This may not need to scan all the time. I've only noticed it when the connection or app was disrupted, so it would only need to scan again on app start, or if it cannot reach the OrangeLink. While scanning on every connect works, perhaps it could be made less aggressive and only try on app start and failure to connect?

2021-04-28 16:31 UTC, andyrozman commented
1st one... It needs to be visible when you open configuration. We don't use dialogs in configuration. Please extend text to "Scan before connecting to OrangeLink, it should improve connections (can also be used with other RileyLink clones, if needed)" and put it into rileylink module (so that can it can be used by both MDT and Omnipod configuration).

2021-04-29 01:58 UTC, bubbledevteam commented
> 1st one... It needs to be visible when you open configuration. We don't use dialogs in configuration. Please extend text to "Scan before connecting to OrangeLink, it should improve connections (can also be used with other RileyLink clones, if needed)" and put it into rileylink module (so that can it can be used by both MDT and Omnipod configuration).

I am a little confused about "put it into rileylink module" you mentioned, is it the place as design 1？If that, I just need to change the text only

2021-04-29 08:48 UTC, andyrozman commented
RileyLink module is used by both Medtronic and Omnipod-Eros, so if you put string into RileyLink module, both pumps can use it. Afterwards you need to change pref_medtronic.xml and omnipod-eros-preferences.xml... This setting needs to be in the main driver settings page, not on the one you have showed...

2021-04-29 11:13 UTC, bubbledevteam commented
> RileyLink module is used by both Medtronic and Omnipod-Eros, so if you put string into RileyLink module, both pumps can use it. Afterwards you need to change pref_medtronic.xml and omnipod-eros-preferences.xml... This setting needs to be in the main driver settings page, not on the one you have showed...

could you pls show me which page？

2021-05-06 18:16 UTC, StephenBrown2 commented
Take a look at the changes done for showing the battery level for Orange/EmaLinks: https://github.com/nightscout/AndroidAPS/pull/430

2021-05-19 23:03 UTC, StephenBrown2 commented
> could you pls show me which page？

You'll need to rebase on `dev`, and then edit the following:
```
omnipod-eros/src/main/res/xml/omnipod_eros_preferences.xml
```

The preferences are exposed in the General preferences page, but (for me) under the medtronic heading. They would show up under omnipod eros settings if that plugin was enabled.

2021-05-25 18:19 UTC, andyrozman commented
Could you please add configuration in main preferences for medtronic and omnipod, instead into this activity. And please close the other PR.
Where you need to put configuration in, is here:
omnipod-eros/src/main/res/xml/omnipod_eros_preferences.xml
/medtronic/src/main/res/xml/pref_medtronic.xml

And please follow @AdrianLxM instructions what needs to be changed.

2021-05-26 10:19 UTC, bubbledevteam commented
> Could you please add configuration in main preferences for medtronic and omnipod, instead into this activity. And please close the other PR.
> Where you need to put configuration in, is here:
> omnipod-eros/src/main/res/xml/omnipod_eros_preferences.xml
> /medtronic/src/main/res/xml/pref_medtronic.xml
> 
> And please follow @AdrianLxM instructions what needs to be changed.

As @StephenBrown2 replied, I need to rebase it on dev, that's why I opened a new one

2021-10-10 07:24 UTC, closed without merging